// Central API route registry. Paths mirror backend `TEDF.API/Endpoints/` (feature-based).
// Object keys are kept stable for the services that consume them; only the URL strings track the backend.
export const routes = {
  auth: {
    session: "/api/auth/session",
  },
  users: {
    me: "/api/users/me",
  },
  admin: {
    dashboard: "/api/dashboard/admin",
    projects: "/api/projects",
    assignDepartmentHead: (departmentId: number) => `/api/users/departments/${departmentId}/head`,
    /** Grant (POST) / revoke (DELETE) the Department Head role for a lecturer. */
    userDepartmentHead: (userId: string) => `/api/users/${userId}/department-head`,
    users: "/api/users",
    usersImport: "/api/users/import",
    usersImportTemplate: "/api/users/import/template",
    activityLogs: "/api/activity-logs",
    activityLogsSummary: "/api/activity-logs/summary",
    errorLogs: "/api/activity-logs/errors",
    errorLogDetail: (id: string) => `/api/activity-logs/errors/${id}`,
    semesters: "/api/semesters",
    /** Same list as `semesters`, readable by any authenticated user (filter dropdowns). */
    semestersPublic: "/api/semesters/public",
    semesterById: (id: number) => `/api/semesters/${id}`,
    activeSemester: "/api/semesters/active",
    eligibleStudentsImport: (id: number) => `/api/semesters/${id}/eligible-students/import`,
    eligibleMentorsImport: (id: number) => `/api/semesters/${id}/eligible-mentors/import`,
    eligibleStudents: (id: number) => `/api/semesters/${id}/eligible-students`,
    eligibleMentors: (id: number) => `/api/semesters/${id}/eligible-mentors`,
    eligibleMentorMajor: (id: number, mentorId: string) => `/api/semesters/${id}/eligible-mentors/${mentorId}/major`,
    eligibleStudentsBulkDelete: (id: number) => `/api/semesters/${id}/eligible-students/bulk-delete`,
    eligibleMentorsBulkDelete: (id: number) => `/api/semesters/${id}/eligible-mentors/bulk-delete`,
    semesterRosterPublish: (id: number) => `/api/semesters/${id}/roster/publish`,
    settings: "/api/settings",
    settingsTestEmail: "/api/settings/test-email",
    settingsLogo: "/api/settings/logo",
    archives: "/api/archives",
    archiveDownload: (id: string) => `/api/archives/${id}/download`,
  },
  common: {
    majors: "/api/majors",
    publicSettings: "/api/settings/public",
    notifications: "/api/notifications",
    unreadNotificationCount: "/api/notifications/unread-count",
  },
  // All role dashboards unified under the `/api/dashboard` feature group.
  dashboard: {
    admin: "/api/dashboard/admin",
    mentor: "/api/dashboard/mentor",
    departmentHead: "/api/dashboard/department-head",
    evaluator: "/api/dashboard/evaluator",
  },
  // Department-head actions are now part of their feature: dashboard→Dashboard, projects→Projects,
  // evaluator-management→Evaluations.
  departmentHead: {
    dashboard: "/api/dashboard/department-head",
    evaluators: "/api/evaluations/evaluators",
    projects: "/api/projects/department",
    auditLogs: "/api/projects/audit-logs",
    assignEvaluator: "/api/evaluations/assign-evaluator",
    finalDecision: (projectId: string) => `/api/evaluations/projects/${projectId}/final-decision`,
  },
  evaluator: {
    dashboard: "/api/dashboard/evaluator",
    filterOptions: "/api/evaluations/filter-options",
    history: "/api/evaluations/history",
    projects: "/api/evaluations/projects",
    review: (projectId: string) => `/api/evaluations/projects/${projectId}/review`,
    similarity: (projectId: string) => `/api/evaluations/projects/${projectId}/similarity`,
    explainSimilarity: (projectId: string) => `/api/evaluations/projects/${projectId}/similarity/explain`,
    evaluate: (projectId: string) => `/api/evaluations/projects/${projectId}/evaluate`,
    checklist: (projectId: string) => `/api/evaluations/projects/${projectId}/checklist`,
    evaluatorChecklist: (projectId: string, evaluatorId: string) =>
      `/api/evaluations/projects/${projectId}/evaluators/${evaluatorId}/checklist`,
  },
  // Department-head managed topic-evaluation checklist configurations.
  checklistConfigs: {
    base: "/api/checklist-configs",
    defaultCriteria: "/api/checklist-configs/default-criteria",
    template: "/api/checklist-configs/template",
    preview: "/api/checklist-configs/preview",
    import: "/api/checklist-configs/import",
    byId: (id: string) => `/api/checklist-configs/${id}`,
    copy: (id: string) => `/api/checklist-configs/${id}/copy`,
    activate: (id: string) => `/api/checklist-configs/${id}/activate`,
    deactivate: (id: string) => `/api/checklist-configs/${id}/deactivate`,
  },
  // Mentor actions distributed into features: dashboard→Dashboard, topics→Topics,
  // update/resubmit→TopicPools, groups→Groups, review→DirectTopics.
  mentor: {
    dashboard: "/api/dashboard/mentor",
    topics: "/api/topics/mentor",
    topicUpdate: (projectId: string) => `/api/topic-pools/topics/${projectId}/update`,
    topicResubmit: (projectId: string) => `/api/topic-pools/topics/${projectId}/resubmit`,
    studentGroups: "/api/groups/mentor",
    supervisedProjects: "/api/projects/supervised",
  },
  studentGroups: {
    base: "/api/groups",
    myGroup: "/api/groups/my-group",
    open: "/api/groups/open",
    myInvitations: "/api/groups/my-invitations",
    myPendingJoinRequest: "/api/groups/my-pending-join-request",
    joinRequests: (groupId: string) => `/api/groups/${groupId}/join-requests`,
    invitableStudents: (groupId: string) => `/api/groups/${groupId}/invitable-students`,
    invitations: (groupId: string) => `/api/groups/${groupId}/invitations`,
    bulkApproveJoinRequests: (groupId: string) => `/api/groups/${groupId}/join-requests/bulk-approve`,
    bulkRejectJoinRequests: (groupId: string) => `/api/groups/${groupId}/join-requests/bulk-reject`,
    leave: (groupId: string) => `/api/groups/${groupId}/members/me`,
    disband: (groupId: string) => `/api/groups/${groupId}`,
  },
  studentTopics: {
    registerTopic: (groupId: string) => `/api/topic-pools/${groupId}/topic-registrations`,
    myRegistrations: (groupId: string) => `/api/topic-pools/groups/${groupId}/registrations`,
    cancelRegistration: (registrationId: string) => `/api/topic-pools/registrations/${registrationId}/cancel`,
  },
  topics: {
    list: "/api/topics",
    detail: (topicId: string) => `/api/topics/${topicId}`,
    documents: (topicId: string) => `/api/topics/${topicId}/documents`,
    registerForm: (topicId: string) => `/api/topics/${topicId}/register-form`,
  },
  topicPools: {
    list: "/api/topic-pools",
    byDepartment: "/api/topic-pools/by-department",
    byId: (id: string) => `/api/topic-pools/${id}`,
    statistics: (id: string) => `/api/topic-pools/${id}/statistics`,
    propose: (poolId: string) => `/api/topic-pools/${poolId}/propose`,
    projectRegistration: (projectId: string) => `/api/topic-pools/projects/${projectId}/registration`,
    mentorRegistrations: "/api/topic-pools/registrations/mentor",
    confirmRegistration: (id: string) => `/api/topic-pools/registrations/${id}/confirm`,
    rejectRegistration: (id: string) => `/api/topic-pools/registrations/${id}/reject`,
    noteAttachment: "/api/topic-pools/note-attachment",
  },
  support: {
    base: "/api/support-tickets",
    stats: "/api/support-tickets/stats",
    ticket: (ticketId: string) => `/api/support-tickets/${ticketId}`,
    reply: (ticketId: string) => `/api/support-tickets/${ticketId}/reply`,
    status: (ticketId: string) => `/api/support-tickets/${ticketId}/status`,
  },
  notifications: {
    list: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    markAllRead: "/api/notifications/read-all",
    markRead: (id: string) => `/api/notifications/${id}/read`,
  },
} as const;
