// Central API route registry. Paths mirror backend `TEDF.API/Endpoints/` (feature-based).
// Object keys are kept stable for the services that consume them; only the URL strings track the backend.
export const routes = {
  admin: {
    dashboard: "/api/dashboard/admin",
    projects: "/api/projects",
    assignDepartmentHead: (departmentId: number) => `/api/users/departments/${departmentId}/head`,
    users: "/api/users",
    activityLogs: "/api/activity-logs",
    groupedActivityLogs: "/api/activity-logs/grouped",
    severitySummary: "/api/activity-logs/severity-summary",
    errorDetails: "/api/activity-logs/errors",
    errorLogDetail: (id: string) => `/api/activity-logs/errors/${id}`,
    semesters: "/api/semesters",
    semesterById: (id: number) => `/api/semesters/${id}`,
    activeSemester: "/api/semesters/active",
    eligibleStudentsImport: (id: number) => `/api/semesters/${id}/eligible-students/import`,
    settings: "/api/settings",
    settingsTestEmail: "/api/settings/test-email",
    settingsLogo: "/api/settings/logo",
    archives: "/api/archives",
    archiveDownload: (id: string) => `/api/archives/${id}/download`,
  },
  common: {
    majors: "/api/majors",
    publicSettings: "/api/settings/public",
    notifications: "/api/notifications",
    unreadNotificationCount: "/api/notifications/unread-count",
  },
  // All role dashboards unified under the `/api/dashboard` feature group.
  dashboard: {
    admin: "/api/dashboard/admin",
    mentor: "/api/dashboard/mentor",
    departmentHead: "/api/dashboard/department-head",
    evaluator: "/api/dashboard/evaluator",
  },
  // Department-head actions are now part of their feature: dashboard→Dashboard, projects→Projects,
  // evaluator-management→Evaluations.
  departmentHead: {
    dashboard: "/api/dashboard/department-head",
    evaluators: "/api/evaluations/evaluators",
    projects: "/api/projects/department",
    assignEvaluator: "/api/evaluations/assign-evaluator",
    finalDecision: (projectId: string) => `/api/evaluations/projects/${projectId}/final-decision`,
  },
  evaluator: {
    dashboard: "/api/dashboard/evaluator",
    filterOptions: "/api/evaluations/filter-options",
    history: "/api/evaluations/history",
    projects: "/api/evaluations/projects",
    review: (projectId: string) => `/api/evaluations/projects/${projectId}/review`,
    similarity: (projectId: string) => `/api/evaluations/projects/${projectId}/similarity`,
    evaluate: (projectId: string) => `/api/evaluations/projects/${projectId}/evaluate`,
  },
  // Mentor actions distributed into features: dashboard→Dashboard, topics→Topics,
  // update/resubmit→TopicPools, groups→Groups, review→DirectTopics.
  mentor: {
    dashboard: "/api/dashboard/mentor",
    topics: "/api/topics/mentor",
    topicUpdate: (projectId: string) => `/api/topic-pools/topics/${projectId}/update`,
    topicResubmit: (projectId: string) => `/api/topic-pools/topics/${projectId}/resubmit`,
    studentGroups: "/api/groups/mentor",
    directRegistrationReview: (projectId: string) => `/api/direct-topics/${projectId}/review`,
  },
  studentGroups: {
    base: "/api/groups",
    myGroup: "/api/groups/my-group",
    open: "/api/groups/open",
    myInvitations: "/api/groups/my-invitations",
    myPendingJoinRequest: "/api/groups/my-pending-join-request",
    joinRequests: (groupId: string) => `/api/groups/${groupId}/join-requests`,
    invitableStudents: (groupId: string) => `/api/groups/${groupId}/invitable-students`,
    invitations: (groupId: string) => `/api/groups/${groupId}/invitations`,
  },
  studentTopics: {
    registerTopic: (groupId: string) => `/api/topic-pools/${groupId}/topic-registrations`,
    createDirectTopic: (groupId: string) => `/api/direct-topics/${groupId}`,
    updateDirectTopic: (projectId: string) => `/api/direct-topics/${projectId}`,
    submitDirectTopicToMentor: (groupId: string, projectId: string) =>
      `/api/direct-topics/${projectId}/submit-to-mentor/${groupId}`,
    availableMentors: "/api/direct-topics/available-mentors",
  },
  topics: {
    list: "/api/topics",
    detail: (topicId: string) => `/api/topics/${topicId}`,
    documents: (topicId: string) => `/api/topics/${topicId}/documents`,
  },
  topicPools: {
    list: "/api/topic-pools",
    byDepartment: "/api/topic-pools/by-department",
    byId: (id: string) => `/api/topic-pools/${id}`,
    statistics: (id: string) => `/api/topic-pools/${id}/statistics`,
    propose: (poolId: string) => `/api/topic-pools/${poolId}/propose`,
    confirmRegistration: (id: string) => `/api/topic-pools/registrations/${id}/confirm`,
    rejectRegistration: (id: string) => `/api/topic-pools/registrations/${id}/reject`,
  },
  support: {
    base: "/api/support-tickets",
    stats: "/api/support-tickets/stats",
    ticket: (ticketId: string) => `/api/support-tickets/${ticketId}`,
    reply: (ticketId: string) => `/api/support-tickets/${ticketId}/reply`,
    status: (ticketId: string) => `/api/support-tickets/${ticketId}/status`,
  },
  notifications: {
    list: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    markAllRead: "/api/notifications/read-all",
    markRead: (id: string) => `/api/notifications/${id}/read`,
  },
} as const;
