export const routes = {
  admin: {
    dashboard: "/api/admin/dashboard",
    projects: "/api/admin/projects",
    users: "/api/admin/users",
    activityLogs: "/api/admin/activity-logs",
    groupedActivityLogs: "/api/admin/activity-logs/grouped",
    severitySummary: "/api/admin/activity-logs/severity-summary",
    errorDetails: "/api/admin/activity-logs/errors",
    errorLogDetail: (id: string) => `/api/admin/error-logs/${id}`,
    semesters: "/api/admin/semesters",
    semesterById: (id: number) => `/api/admin/semesters/${id}`,
    activeSemester: "/api/admin/semesters/active",
    eligibleStudentsImport: (id: number) => `/api/admin/semesters/${id}/eligible-students/import`,
    settings: "/api/admin/settings",
    settingsTestEmail: "/api/admin/settings/test-email",
    settingsLogo: "/api/admin/settings/logo",
    archives: "/api/admin/archives",
    archiveDownload: (id: string) => `/api/admin/archives/${id}/download`,
  },
  common: {
    majors: "/api/majors",
    publicSettings: "/api/settings/public",
    notifications: "/api/notifications",
    unreadNotificationCount: "/api/notifications/unread-count",
  },
  dashboard: {
    mentor: "/api/mentor/dashboard",
    departmentHead: "/api/department-head/dashboard",
  },
  departmentHead: {
    dashboard: "/api/department-head/dashboard",
    evaluators: "/api/department-head/evaluators",
    projects: "/api/department-head/projects",
    assignEvaluator: "/api/department-head/assign-evaluator",
    finalDecision: (projectId: string) => `/api/department-head/projects/${projectId}/final-decision`,
  },
  evaluator: {
    dashboard: "/api/evaluator/dashboard",
    filterOptions: "/api/evaluator/filter-options",
    history: "/api/evaluator/history",
    projects: "/api/evaluator/projects",
    review: (projectId: string) => `/api/evaluator/projects/${projectId}/review`,
    similarity: (projectId: string) => `/api/evaluator/projects/${projectId}/similarity`,
    evaluate: (projectId: string) => `/api/evaluator/projects/${projectId}/evaluate`,
  },
  mentor: {
    dashboard: "/api/mentor/dashboard",
    topics: "/api/mentor/topics",
    topicUpdate: (projectId: string) => `/api/mentor/topics/${projectId}/update`,
    topicResubmit: (projectId: string) => `/api/mentor/topics/${projectId}/resubmit`,
    studentGroups: "/api/mentor/student-groups",
    directRegistrationReview: (projectId: string) => `/api/mentor/direct-registration/${projectId}/review`,
  },
  studentGroups: {
    base: "/api/student-groups",
    myGroup: "/api/student-groups/my-group",
    open: "/api/student-groups/open",
    myInvitations: "/api/student-groups/my-invitations",
    myPendingJoinRequest: "/api/student-groups/my-pending-join-request",
    joinRequests: (groupId: string) => `/api/student-groups/${groupId}/join-requests`,
    invitableStudents: (groupId: string) => `/api/student-groups/${groupId}/invitable-students`,
    invitations: (groupId: string) => `/api/student-groups/${groupId}/invitations`,
  },
  studentTopics: {
    registerTopic: (groupId: string) => `/api/student/${groupId}/topic-registrations`,
    createDirectTopic: (groupId: string) => `/api/student/${groupId}/propose-topic`,
    updateDirectTopic: (projectId: string) => `/api/student/propose-topic/${projectId}/update`,
    submitDirectTopicToMentor: (groupId: string, projectId: string) =>
      `/api/student/propose-topic/${groupId}/${projectId}/submit-to-mentor`,
    availableMentors: "/api/student/available-mentors",
  },
  topics: {
    list: "/api/topics",
    detail: (topicId: string) => `/api/topics/${topicId}`,
    documents: (topicId: string) => `/api/topics/${topicId}/documents`,
  },
  topicPools: {
    list: "/api/topic-pools",
    byDepartment: "/api/topic-pools/by-department",
    byId: (id: string) => `/api/topic-pools/${id}`,
    statistics: (id: string) => `/api/topic-pools/${id}/statistics`,
    propose: (poolId: string) => `/api/topic-pools/${poolId}/propose`,
    confirmRegistration: (id: string) => `/api/topic-pools/registrations/${id}/confirm`,
    rejectRegistration: (id: string) => `/api/topic-pools/registrations/${id}/reject`,
  },
  support: {
    base: "/api/supports",
    stats: "/api/supports/stats",
    ticket: (ticketId: string) => `/api/supports/${ticketId}`,
    reply: (ticketId: string) => `/api/supports/${ticketId}/reply`,
    status: (ticketId: string) => `/api/supports/${ticketId}/status`,
  },
  notifications: {
    list: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    markAllRead: "/api/notifications/read-all",
    markRead: (id: string) => `/api/notifications/${id}/read`,
  },
} as const;