// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TEDF.Persistence.SqlServer;

#nullable disable

namespace TEDF.Persistence.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20260325143000_UpdateProjectsGroupIdConstraintForDirectRegistration")]
  partial class UpdateProjectsGroupIdConstraintForDirectRegistration
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
      // Reuse the current model snapshot because this migration only changes SQL constraints.
      new SnapshotProxy().Build(modelBuilder);
    }

    private sealed class SnapshotProxy : AppDbContextModelSnapshot
    {
      public void Build(ModelBuilder modelBuilder)
      {
        BuildModel(modelBuilder);
      }
    }
  }
}
